// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwcCvxZjFMd8f1REUkDxX43Ik_MgOGZ_c',
    appId: '1:140660325207:android:e71953c971d9240ad95c12',
    messagingSenderId: '140660325207',
    projectId: 'caixinha-troia',
    databaseURL: 'https://caixinha-troia-default-rtdb.firebaseio.com',
    storageBucket: 'caixinha-troia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBknYJvUzxxEQMPxb2yp8sU33p7DMEA720',
    appId: '1:140660325207:ios:f8698912b33d2cf1d95c12',
    messagingSenderId: '140660325207',
    projectId: 'caixinha-troia',
    databaseURL: 'https://caixinha-troia-default-rtdb.firebaseio.com',
    storageBucket: 'caixinha-troia.appspot.com',
    iosClientId: '140660325207-qdjc7aemo3fip33hrg9i34rjo14bc3vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.caixinhaTroia',
  );
}
